### ISSUE TITLE
References to com.billynewport should be removed?

### ISSUE THREAD

**Issue by tedkirby** [bnewport/Samples#2]
Importing chirp-web into eclipse gives:

Unbound classpath variable: 'M2_REPO/com/billynewport/wxsutils/wxsutils/1.3-SNAPSHOT/wxsutils-1.3-SNAPSHOT.jar' in project 'chirp-webapp'   chirp-webapp        

building chirp-web add with mvn gives:

Missing:

2) com.billynewport.wxsutils:wxsutils:jar:1.0-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=com.billynewport.wxsutils -DartifactId=wxsutils -Dversion=1
.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=com.billynewport.wxsutils -DartifactId=wxsutils -Dversion=1.0
-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
        1) com.billynewport:chirp-webapp:war:1.1-SNAPSHOT
        2) com.billynewport.wxsutils:wxsutils:jar:1.0-SNAPSHOT

It seems all the package names should be com.devwebsphere?

**Comment by bnewport** [comment]
This kind of evolved as I got familiar with how I wanted to do it. I've too much code using the various conventions now to change it.
