### ISSUE TITLE
public static String DATASLOT = JDBCTxCallback.class.getName();

### ISSUE THREAD

**Issue by davidkarlsen** [bnewport/Samples#3]
What's the meaning with these constants, as the slot is reserved through objectGrid.reserveSlot( TxID.SLOT_NAME ); ?

**Comment by fraenkel** [comment]
See the documentation on
[reserveSlot](http://www-01.ibm.com/support/knowledgecenter/SSTVLU_8.6.0/com.ibm.websphere.extremescale.javadoc.doc/topics/com/ibm/websphere/objectgrid/ObjectGrid.html%23reserveSlot%28java.lang.String%29)

[TxID.SLOT_NAME](http://www-01.ibm.com/support/knowledgecenter/SSTVLU_8.6.0/com.ibm.websphere.extremescale.javadoc.doc/topics/com/ibm/websphere/objectgrid/TxID.html%23SLOT_NAME)
